In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

In [2]:
df1 = pd.read_csv(
    '../data/consumer_transanctions.csv',
    dtype={'consumer_session_id': str}
)

In [3]:
df2 = pd.read_csv('../data/platform_content.csv')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72312 entries, 0 to 72311
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   event_timestamp       72312 non-null  int64
 1   interaction_type      72312 non-null  object
 2   item_id               72312 non-null  int64
 3   consumer_id           72312 non-null  int64
 4   consumer_session_id   72312 non-null  object
 5   consumer_device_info  56918 non-null  object
 6   consumer_location     56907 non-null  object
 7   country               56918 non-null  object
dtypes: int64(3), object(5)
memory usage: 4.4+ MB

In [5]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3122 entries, 0 to 3121
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   event_timestamp       3122 non-null   int64
 1   interaction_type      3122 non-null   object
 2   item_id               3122 non-null   int64
 3   producer_id           3122 non-null   int64
 4   producer_session_id   3122 non-null   int64
 5   producer_device_info  680 non-null    object
 6   producer_location     680 non-null    object
 7   producer_country      680 non-null    object
 8   item_type             3122 non-null   object
 9   item_url              3122 non-null   object
 10  title                 3122 non-null   object
 11  text_description      3122 non-null   object
 12  language              3122 non-null   object
dtypes: int64(4), object(9)
memory usage: 317.2+ KB

In [6]:
df = df1.merge(df2, on='item_id')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72680 entries, 0 to 72679
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   event_timestamp_x     72680 non-null  int64
 1   interaction_type_x    72680 non-null  object
 2   item_id               72680 non-null  int64
 3   consumer_id           72680 non-null  int64
 4   consumer_session_id   72680 non-null  object
 5   consumer_device_info  57184 non-null  object
 6   consumer_location     57173 non-null  object
 7   country               57184 non-null  object
 8   event_timestamp_y     72680 non-null  int64
 9   interaction_type_y    72680 non-null  object
 10  producer_id           72680 non-null  int64
 11  producer_session_id   72680 non-null  int64
 12  producer_device_info  15254 non-null  object
 13  producer_location     15254 non-null  object
 14  producer_country      15254 non-null  object
 15  item_type             72680 non-null  object
 16  item_url              72680 non-null  object
 17  title                 72680 non-null  object
 18  text_description      72680 non-null  object
 19  language              72680 non-null  object
dtypes: int64(6), object(14)
memory usage: 11.1+ MB

In [8]:
df.head()

,event_timestamp_x,interaction_type_x,item_id,consumer_id,consumer_session_id,consumer_device_info,consumer_location,country,event_timestamp_y,interaction_type_y,producer_id,producer_session_id,producer_device_info,producer_location,producer_country,item_type,item_url,title,text_description,language
0,1465413032,content_watched,-3499919498720038879,-8845298781299428018,1264196770339959068,NaN,NaN,NaN,1465309434,content_present,-1032019229384696495,-7696592431575292648,NaN,NaN,NaN,HTML,http://techcrunch.com/2016/06/07/hiri/,Hiri wants to fix the workplace email problem,Hiri is the latest startup trying to fix email...,en
1,1465412560,content_watched,8890720798209849691,-1032019229384696495,3621737643587579081,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2...,NY,US,1465223368,content_present,1895326251577378793,-1847389231177111235,NaN,NaN,NaN,HTML,https://www.nngroup.com/articles/top-intranet-...,Top 10 Intranet Trends of 2016,"Summary: Hero images, carousels, fat footers, ...",en
2,1465416190,content_watched,310515487419366995,-1130272294246983140,2631864456530402479,NaN,NaN,NaN,1465396491,content_present,-5527145562136413747,3192880191028684629,NaN,NaN,NaN,HTML,http://blog.runrun.it/erros-de-portugues-em-e-...,71 erros de português que precisam sumir dos s...,Escrever um e-mail não deveria ser uma coisa t...,pt
3,1465413895,content_followed,310515487419366995,344280948527967603,-3167637573980064150,NaN,NaN,NaN,1465396491,content_present,-5527145562136413747,3192880191028684629,NaN,NaN,NaN,HTML,http://blog.runrun.it/erros-de-portugues-em-e-...,71 erros de português que precisam sumir dos s...,Escrever um e-mail não deveria ser uma coisa t...,pt
4,1465412290,content_watched,-7820640624231356730,-445337111692715325,561148 1178424124714,NaN,NaN,NaN,1465411724,content_present,-1032019229384696495,3621737643587579081,NaN,NaN,NaN,HTML,http://www.fastcompany.com/3058876/your-most-p...,How This Googler Redesigned The Workweek,Jake Knapp has always been concerned about the...,en

In [9]:
df['interaction_type_x'].unique()

array(['content_watched', 'content_followed', 'content_saved',
       'content_liked', 'content_commented_on'], dtype=object)

In [10]:
df['interaction_type_y'].unique() # no need for collaborative filering

array(['content_present', 'content_pulled_out'], dtype=object)

In [11]:
df['producer_country'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 72680 entries, 0 to 72679
Series name: producer_country
Non-Null Count  Dtype
--------------  -----
15254 non-null  object
dtypes: object(1)
memory usage: 567.9+ KB

In [12]:
df['producer_country'].unique()

array([nan, 'BR', 'CA', 'US', 'AU', 'PT'], dtype=object)

In [13]:
print(df['producer_country'].value_counts())

producer_country
BR    14089
US     1035
CA      107
AU       14
PT        9
Name: count, dtype: int64

In [14]:
print(df.columns)

Index(['event_timestamp_x', 'interaction_type_x', 'item_id', 'consumer_id',
       'consumer_session_id', 'consumer_device_info', 'consumer_location',
       'country', 'event_timestamp_y', 'interaction_type_y', 'producer_id',
       'producer_session_id', 'producer_device_info', 'producer_location',
       'producer_country', 'item_type', 'item_url', 'title',
       'text_description', 'language'],
      dtype='object')

In [15]:
# ['event_timestamp_x', 'interaction_type_x', 'item_id', 'consumer_id',
#        'consumer_session_id', 'consumer_device_info', 'consumer_location',
#        'country', 'event_timestamp_y', 'interaction_type_y', 'producer_id',
#        'producer_session_id', 'producer_device_info', 'producer_location',
#        'producer_country', 'item_type', 'item_url', 'title',
#        'text_description', 'language']

df = df[[#'event_timestamp_x',
         #'interaction_type_x', 
        'item_id', 'consumer_id',
       #'consumer_session_id', 'consumer_device_info', 
        'consumer_location',
       'country', 
        #'event_timestamp_y', 'interaction_type_y', 
        'producer_id', 'producer_session_id', 
        #'producer_device_info', 
        'producer_location', 'producer_country', 'item_type', 'item_url', 'title',
       'text_description', 'language']]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72680 entries, 0 to 72679
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   item_id              72680 non-null  int64
 1   consumer_id          72680 non-null  int64
 2   consumer_location    57173 non-null  object
 3   country              57184 non-null  object
 4   producer_id          72680 non-null  int64
 5   producer_session_id  72680 non-null  int64
 6   producer_location    15254 non-null  object
 7   producer_country     15254 non-null  object
 8   item_type            72680 non-null  object
 9   item_url             72680 non-null  object
 10  title                72680 non-null  object
 11  text_description     72680 non-null  object
 12  language             72680 non-null  object
dtypes: int64(4), object(9)
memory usage: 7.2+ MB

## Data Cleaning

In [17]:
df.duplicated().sum()

np.int64(20781)

In [18]:
df = df.drop_duplicates()

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 51899 entries, 0 to 72679
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   item_id              51899 non-null  int64
 1   consumer_id          51899 non-null  int64
 2   consumer_location    40623 non-null  object
 3   country              40633 non-null  object
 4   producer_id          51899 non-null  int64
 5   producer_session_id  51899 non-null  int64
 6   producer_location    9843 non-null   object
 7   producer_country     9843 non-null   object
 8   item_type            51899 non-null  object
 9   item_url             51899 non-null  object
 10  title                51899 non-null  object
 11  text_description     51899 non-null  object
 12  language             51899 non-null  object
dtypes: int64(4), object(9)
memory usage: 5.5+ MB

In [20]:
df.head()

,item_id,consumer_id,consumer_location,country,producer_id,producer_session_id,producer_location,producer_country,item_type,item_url,title,text_description,language
0,-3499919498720038879,-8845298781299428018,NaN,NaN,-1032019229384696495,-7696592431575292648,NaN,NaN,HTML,http://techcrunch.com/2016/06/07/hiri/,Hiri wants to fix the workplace email problem,Hiri is the latest startup trying to fix email...,en
1,8890720798209849691,-1032019229384696495,NY,US,1895326251577378793,-1847389231177111235,NaN,NaN,HTML,https://www.nngroup.com/articles/top-intranet-...,Top 10 Intranet Trends of 2016,"Summary: Hero images, carousels, fat footers, ...",en
2,310515487419366995,-1130272294246983140,NaN,NaN,-5527145562136413747,3192880191028684629,NaN,NaN,HTML,http://blog.runrun.it/erros-de-portugues-em-e-...,71 erros de português que precisam sumir dos s...,Escrever um e-mail não deveria ser uma coisa t...,pt
3,310515487419366995,344280948527967603,NaN,NaN,-5527145562136413747,3192880191028684629,NaN,NaN,HTML,http://blog.runrun.it/erros-de-portugues-em-e-...,71 erros de português que precisam sumir dos s...,Escrever um e-mail não deveria ser uma coisa t...,pt
4,-7820640624231356730,-445337111692715325,NaN,NaN,-1032019229384696495,3621737643587579081,NaN,NaN,HTML,http://www.fastcompany.com/3058876/your-most-p...,How This Googler Redesigned The Workweek,Jake Knapp has always been concerned about the...,en

In [21]:
df.tail()

,item_id,consumer_id,consumer_location,country,producer_id,producer_session_id,producer_location,producer_country,item_type,item_url,title,text_description,language
72669,-6590819806697898649,-9016528795238256703,MG,BR,-4465926797008424436,-7541317811547099244,SP,BR,HTML,https://medium.com/android-dev-br/listas-com-r...,Listas com RecyclerView - Android Dev BR,Lista simples O primeiro passo é colocar o Rec...,pt
72670,-2069509552243850466,-9196668942822132778,SP,BR,3609194402293569455,-1454522461531275738,NaN,NaN,HTML,https://msdn.microsoft.com/pt-br/virtualizatio...,Contêiner do Windows no Windows 10,O exercício vai guiá-lo pela implantação e uso...,pt
72671,3770082505811422124,5713241217519616260,MG,BR,3609194402293569455,-344378995821744418,SP,BR,HTML,https://www.embarcados.com.br/webinar-internet...,Webinar: A Internet das Coisas no Brasil,20 bilhões de equipamentos eletrônicos conecta...,pt
72677,-1999468346928419252,-9196668942822132778,SP,BR,3609194402293569455,2769014915644964260,SP,BR,HTML,https://goto.docker.com/DockerDatacenterforAWS...,"Docker - Build, Ship, and Run Any App, Anywhere",AWS users are now using Docker containers to h...,en
72679,5669290109546991426,5713241217519616260,MG,BR,3609194402293569455,4233710150736291687,SP,BR,HTML,http://www.digitaltrends.com/cool-tech/101hero...,"Signs suggest that 101Hero, the $49 3D printer...",Questions mount on both delivery and productio...,en

In [22]:
df.reset_index(drop=True, inplace=True)

In [23]:
df.tail()

,item_id,consumer_id,consumer_location,country,producer_id,producer_session_id,producer_location,producer_country,item_type,item_url,title,text_description,language
51894,-6590819806697898649,-9016528795238256703,MG,BR,-4465926797008424436,-7541317811547099244,SP,BR,HTML,https://medium.com/android-dev-br/listas-com-r...,Listas com RecyclerView - Android Dev BR,Lista simples O primeiro passo é colocar o Rec...,pt
51895,-2069509552243850466,-9196668942822132778,SP,BR,3609194402293569455,-1454522461531275738,NaN,NaN,HTML,https://msdn.microsoft.com/pt-br/virtualizatio...,Contêiner do Windows no Windows 10,O exercício vai guiá-lo pela implantação e uso...,pt
51896,3770082505811422124,5713241217519616260,MG,BR,3609194402293569455,-344378995821744418,SP,BR,HTML,https://www.embarcados.com.br/webinar-internet...,Webinar: A Internet das Coisas no Brasil,20 bilhões de equipamentos eletrônicos conecta...,pt
51897,-1999468346928419252,-9196668942822132778,SP,BR,3609194402293569455,2769014915644964260,SP,BR,HTML,https://goto.docker.com/DockerDatacenterforAWS...,"Docker - Build, Ship, and Run Any App, Anywhere",AWS users are now using Docker containers to h...,en
51898,5669290109546991426,5713241217519616260,MG,BR,3609194402293569455,4233710150736291687,SP,BR,HTML,http://www.digitaltrends.com/cool-tech/101hero...,"Signs suggest that 101Hero, the $49 3D printer...",Questions mount on both delivery and productio...,en

In [25]:
pickle.dump(df, open('../data/processed_df.pkl', 'wb'))